### ISSUE TITLE
Support Multiple Canvas Views?

### ISSUE THREAD

**Issue by triniwiz** [triniwiz/nativescript-canvas-plugin#25]
To be or not to be, that is the question:
Whether 'tis nobler to support multiple views .......

**Comment by xtronoid** [comment]
this is nice because each canvas/renderer is a thread, and sometimes is cool and needed to do this... it´s a well conceived technique on ibm site for obviously ppl that make games for example ( and even some special app ) ... as one background canvas is the background (less updated), and the front one is less throttled (faster fps), this natural parallelism is nice (because separated threads)

another thing to mention is.. when using nativescript webview to open a renderer... it already runs in a separated thread (from a javascript point of view, for example loading some data in nativescript, putting into internal chip, then loading via webview context without needing a worker for it), for example in browser not webview, you really need another worker for loader...

i hope i was not so obscure in the explanation
